name:               "Taylor Chen"
baseurl:            ""
permalink:          /:year/:month/:day/:title
markdown:           rdiscount

# Navigation
nav:
  - name:           "Portfolio"
    href:           "http://taylorchen.com/"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
